Added ability to provide template for device names
marthoc/homeseer pull request #3
Opened 2020-04-21 05:20 UTC by AndreBremer

Added a new configuration option `name_template`. 

The Jinja2 template can be used to evaluate device properties when constructing device names for HomeAssistant. This gives users more flexibility in ensuring that HomeSeer device names match their existing HomeAssistant naming scheme (for example, I don't need location2, but I separate room and device name with a hyphen). The behavior of this new option is consistent with existing functionality, including `location_names`.

The default template is `{{ device.name }}` which matches existing default names. The most obvious choice for users is to use locations (for example `{{ device.location }} - {{ device.name }}`). 

When `location_names` is set to `True` it will take precedence over any user `name_template` and override the template effectively to `{{ device.location2 }} {{ device.location }} {{ device.name }}`. This ensures backwards compatibility. 

If backwards compatibility is not a concern, I would suggest removing `location_names` completely, as its behavior can be replicated with `name_template`.

2020-04-21 14:06 UTC, marthoc commented
Please see issue #4. Your comments would be appreciated.

2020-04-26 18:49 UTC, marthoc requested changes

2020-04-26 18:49 UTC, marthoc commented on binary_sensor.py
> +        return self._connection.name_template.render(device = self._device)
Two questions:

1) should this be ```return await render_async...```?

2) what exception is raised if the user inputs an invalid template? Maybe best to do a catch-all except like:
```python
try:
    return await self._connection.name_template.render_async(device = self._device)
except:
    return f"{self._device.location2} {self._device.location} {self._device.name}"
```
Otherwise I would be concerned that an improper template would return a strange name and screw up the registry.

2020-04-26 21:30 UTC, AndreBremer commented on binary_sensor.py
> +        return self._connection.name_template.render(device = self._device)
1. This is only necessary if the template performs blocking I/O. In this case, 'device' is the only input and none of the properties are I/O bound. Therefore, "render" would never yield even if it were async.
2. I already made a change locally to test the template during initialization with test inputs. Probably better than plowing on with unintended results.

2020-04-26 23:09 UTC, marthoc commented on binary_sensor.py
> +        return self._connection.name_template.render(device = self._device)
Re 2: just checked and HA has a built in config validation function for template so we should use that?

2020-04-27 03:54 UTC, AndreBremer commented on binary_sensor.py
> +        return self._connection.name_template.render(device = self._device)
Good catch! I'll put it in.

2020-04-27 05:07 UTC, AndreBremer commented
The template validation change introduced an issue. Please hold until I have a fix.

2020-04-27 05:20 UTC, AndreBremer commented
Turns out, once I used HA's template helper, I had to change everything to async_render anyway, since the helper's implementation doesn't work without it. Everything should work now.

2020-04-27 13:57 UTC, marthoc approved these changes

2020-04-27 13:59 UTC, marthoc commented
@AndreBremer - looks good! Thanks!

2020-04-27 14:03 UTC, merged